Generated by Django 5.0.4 on 2024-04-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200, verbose_name='English')),
                ('uzbek', models.CharField(max_length=200, verbose_name='Uzbek')),
            ],
        ),
    ]
